name: Build IPA

on: [push]  # Fix: Use brackets and proper indentation

jobs:
  build:
    runs-on: macos-latest  # Fix: Use "macos-latest" (not "micro-latest")
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Fix: Use checkout@v4

      - name: Unzip iOS Source
        run: |
          tar -xzf ios_source.tar.gz -C .

      - name: Install Xcode
        run: |
          sudo xcode-select -s /Applications/Xcode_15.2.app/Contents/Developer
          sudo xcodebuild -license accept

      - name: Build and Archive
        run: |
          cd ios_source
          xcodebuild -scheme "TTC" -destination 'generic/platform=iOS' -archivePath TTC.xcarchive archive
          xcodebuild -exportArchive -archivePath TTC.xcarchive -exportPath . -exportOptionsPlist ExportOptions.plist

      - name: Upload IPA
        uses: actions/upload-artifact@v3  # Fix: Use v3 (not v2)
        with:
          name: TTC.ipa
          path: ios_source/TTC.ipa
